---
- name: Download and extract stable NetBox release
  unarchive:
    src: "{{ netbox_stable_uri }}"
    dest: "{{ netbox_releases_path }}"
    creates: "{{ netbox_stable_path }}"
    owner: "{{ netbox_user }}"
    group: "{{ netbox_group }}"
    remote_src: True

- name: Set NetBox deploy path
  set_fact:
    netbox_deploy_path: "{{ netbox_stable_path }}"
